title: "Practical Statistical Learning"
summary: "A series of topics in practical statistical learning with math breakdowns and full Python example codes."
topics: []
published: false
price: 0
toc_depth: 2
allow_override: true
chapters:
  - multiple_linear_regression
